---
- name: Copy from Prod Validator to Temp Validator
  hosts: voting_validator
  vars:
    ledger_location: /ledger
    staked_identity_location_folder: /home/sol
    scp_username: sol
    hotspare_ip: 10.0.0.3
    staked_identity_pubkey: {IDENTITYPUBKEY}
  roles:
    - solana_validator

- name: Apply Transition to Temp Validator
  hosts: hotspare_target
  vars:
    ledger_location: /ledger
    staked_identity_location_folder: /home/sol
    staked_identity_location: /home/sol/staked-identity.json
  roles:
    - apply_transition
